export const projects = [
  {
    title: 'Crypto Hunter',
    description: 'Find your favorite Cryptocurrencies on Crypto Hunter.',
    image: '/images/1.png',
    tags: ['React', 'Material-UI','Firebase', 'API'],
    source: 'https://jc-crypto-hunter.netlify.app',
    visit: 'https://github.com/jonoman55/crypto-hunter',
    id: 1,
  },
  {
    title: 'Cryptoverse',
    description: 'Check the latest Cryptocurrency data, news, and more.',
    image: '/images/2.png',
    tags: ['React/Redux','Ant Design', 'API'],
    source: 'https://jc-cryptoverse.netlify.app',
    visit: 'https://github.com/jonoman55/cryptoverse',
    id: 2,
  },
  {
    title: 'JC Dev Blog',
    description: 'Check out React, Next.js, web dev blog articles, and share your comments.',
    image: '/images/3.png',
    tags: ['NextJS', 'GraphQL', 'TailwindCSS'],
    source: 'https://jc-dev-blog.vercel.app',
    visit: 'https://github.com/jonoman55/jc-dev-blog',
    id: 3,
  },
  {
    title: 'COVID-19 Tracker',
    description: 'Check current COVID statistics by Country or Globally.',
    image: '/images/4.png',
    tags: ['React', 'Material-UI', 'API'],
    source: 'https://jc-dev-covid-tracker.netlify.app',
    visit: 'https://github.com/jonoman55/covid-19-tracker',
    id: 4,
  },
  {
    title: 'Online Pokédex',
    description: 'Search for your favorite Pokémon with the Online Pokédex.',
    image: '/images/5.png',
    tags: ['React', 'Material-UI', 'API'],
    source: 'https://jc-mui-online-pokedex.netlify.app',
    visit: 'https://github.com/jonoman55/material-ui-pokedex',
    id: 5,
  },
  {
    title: 'Rockstar Status Page',
    description: 'Check the Rockstar Services Status in real-time.',
    image: '/images/6.png',
    tags: ['React', 'Material-UI','Full-Stack'],
    source: 'https://jc-rockstar-status-page.netlify.app',
    visit: 'https://github.com/jonoman55/rockstar-status-page',
    id: 6,
  },
  {
    title: 'Travel Advisor',
    description: 'Find your favorite places with Travel Advisor.',
    image: '/images/7.png',
    tags: ['React', 'Material-UI', 'Google APIs'],
    source: 'https://jc-travel-advisor.netlify.app',
    visit: 'https://github.com/jonoman55/travel-advisor',
    id: 7,
  },
  {
    title: 'Entertainment Hub',
    description: 'Find your favorite places with Travel Advisor.',
    image: '/images/8.png',
    tags: ['React', 'Material-UI', 'Context API'],
    source: 'https://jc-entertainment-hub.netlify.app',
    visit: 'https://github.com/jonoman55/entertainment-hub',
    id: 8,
  },
  {
    title: 'AED Realestate Finder',
    description: 'Find, Buy and Own Your Dream Home or Search for Rental Homes in the UAE.',
    image: '/images/9.png',
    tags: ['NextJS', 'Chakra UI', 'APIs'],
    source: 'https://aed-realestate-finder.vercel.app',
    visit: 'https://github.com/jonoman55/aed-realestate-finder',
    id: 9,
  },
  {
    title: 'Vue COVID Tracker',
    description: 'Track daily covid-19 cases and deaths globally or by country.',
    image: '/images/10.png',
    tags: ['Vue', 'TailwindCSS', 'API'],
    source: 'https://jc-covid19-tracker.netlify.app',
    visit: 'https://github.com/jonoman55/vue-covid-tracker',
    id: 10,
  },
];

export const TimeLineData = [
  { year: 2015, text: 'Started my journey as a developer', },
  { year: 2016, text: 'Worked as a developer in industry', },
  { year: 2019, text: 'Founded jc-dev', },
  { year: 2020, text: 'Shared my projects with the world', },
  { year: 2021, text: 'Started my own platform', },
  { year: 2022, text: 'Created my own Blog' }
];